# Generated by Django 4.1.7 on 2023-03-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(choices=[(None, 'Unknown'), ('justice_league', 'Justice League'), ('the_seven', 'The Seven'), ('doom_patrol', 'Doom Patrol'), ('no_team', 'No team provided')], default='no_team', max_length=20, verbose_name='hero`s team name')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='hero name')),
                ('alias', models.CharField(max_length=50, unique=True, verbose_name='hero`s real name')),
                ('is_active', models.BooleanField(default=True, verbose_name='hero`s activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='heroes_app.team', verbose_name='hero`s team')),
            ],
        ),
    ]
